#!/usr/bin/env python3
import click
from funnelback.licence.cli import licence
from funnelback.roles.cli import roles


@click.group()
def cli():
    pass


cli.add_command(licence)
cli.add_command(roles)
cli()
